<?xml version="1.0" ?>

<!-- some links:
  realsense d415 features:
  https://www.framos.com/en/depth-camera-d415-starter-kit-20745?gclid=EAIaIQobChMIkvT-tpbu7wIV23wrCh3kDAV8EAAYASAAEgIDAvD_BwE

  By: Subash Ghimire
  
-->
<robot name="humanoid_rover" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find humanoid_rover)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find humanoid_rover)/urdf/humanoid_rover.gazebo.xacro"/>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.010" rpy="0 0 -1.5708"/>
  </joint>

  <link
    name="base_link">
    <inertial>
      <origin
        xyz="0.0015219 0.0024963 0.35396"
        rpy="0 0 0" />
      <mass
        value="23.445" />
      <inertia
        ixx="0.70999"
        ixy="-0.0026601"
        ixz="0.0012174"
        iyy="0.66023"
        iyz="0.1118"
        izz="0.40877" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://humanoid_rover/meshes/humanoid_rover.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://humanoid_rover/meshes/humanoid_rover.STL" />
      </geometry>
    </collision>
  </link>

  <link
    name="left_wheel">
    <inertial>
      <origin
        xyz="-2.22044604925031E-16 -1.11022302462516E-16 -0.00743620200979157"
        rpy="0 0 0" />
      <mass
        value="0.0457219540821825" />
      <inertia
        ixx="3.44093168862476E-05"
        ixy="-7.6232965252887E-21"
        ixz="-7.10902349155833E-21"
        iyy="3.44093168862476E-05"
        iyz="-7.38192958101574E-21"
        izz="6.75162389361224E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://humanoid_rover/meshes/left_wheel.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.666666666666667 0.694117647058824 0.764705882352941 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://humanoid_rover/meshes/left_wheel.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="left_wheel_joint"
    type="continuous">
    <origin
      xyz="-0.17487 -0.093785 0.0283"
      rpy="1.5708 -0.15525 -1.5708" />
    <!-- <origin
      xyz="-0.17487 -0.093785 0.0283"
      rpy="1.5708 -0.15525 1.5708" />  -->
    <parent
      link="base_link" />
    <child
      link="left_wheel" />
    <axis
      xyz="0 0 1" />
  </joint>
  <link
    name="right_wheel">
    <inertial>
      <origin
        xyz="0 0 0.0135637979902088"
        rpy="0 0 0" />
      <mass
        value="0.0457219540821825" />
      <inertia
        ixx="3.44093168862476E-05"
        ixy="1.6940658945086E-21"
        ixz="-1.59169548806274E-20"
        iyy="3.44093168862476E-05"
        iyz="4.71916451121294E-21"
        izz="6.75162389361224E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://humanoid_rover/meshes/right_wheel.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.666666666666667 0.694117647058824 0.764705882352941 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://humanoid_rover/meshes/right_wheel.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="right_wheel_joint"
    type="continuous">
    <origin
      xyz="0.15387 -0.093785 0.0283"
      rpy="1.5708 -0.35032 1.5708" />
    <parent
      link="base_link" />
    <child
      link="right_wheel" />
    <axis
      xyz="0 0 -1" />
  </joint>
  <link
    name="caster_1">
    <inertial>
      <origin
        xyz="-1.30324219041467E-07 0.0325686390222996 0.00179667483591656"
        rpy="0 0 0" />
      <mass
        value="0.027034514982336" />
      <inertia
        ixx="4.65443465407815E-06"
        ixy="-1.14455606296737E-10"
        ixz="-7.24920838075179E-11"
        iyy="6.78295667634225E-06"
        iyz="4.76148961501701E-08"
        izz="5.59297102707176E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://humanoid_rover/meshes/caster_1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.666666666666667 0.694117647058824 0.764705882352941 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://humanoid_rover/meshes/caster_1.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="caster_1_joint"
    type="continuous">
    <origin
      xyz="0 0.17872 -0.00023602"
      rpy="1.5708 0 1.1228" />
    <parent
      link="base_link" />
    <child
      link="caster_1" />
    <axis
      xyz="0 1 0" />
  </joint>
  <link
    name="caster_2">
    <inertial>
      <origin
        xyz="2.88602883619093E-06 -3.46944695195361E-17 -1.11022302462516E-16"
        rpy="0 0 0" />
      <mass
        value="0.0646267880384706" />
      <inertia
        ixx="1.60367344138628E-05"
        ixy="-6.35274710440725E-22"
        ixz="1.27054942088145E-21"
        iyy="1.61100772675845E-05"
        iyz="-3.49401090742399E-21"
        izz="1.61100772675845E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://humanoid_rover/meshes/caster_2.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.666666666666667 0.694117647058824 0.764705882352941 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://humanoid_rover/meshes/caster_2.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="caster_2_joint"
    type="continuous">
    <origin
      xyz="0 0.00456 0.014907"
      rpy="2.5646 0 0" />
    <parent
      link="caster_1" />
    <child
      link="caster_2" />
    <axis
      xyz="1 0 0" />
  </joint>


<joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="0 0 0.284" rpy="0 0 1.57"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://humanoid_rover/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>



  <!-- model of the realsense camera with different sensors its has and their frames -->
  <!-- <xacro:macro name="sensor_d415" params="name:=camera parent:=base_link"> -->
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
  <xacro:property name="d415_cam_depth_to_left_ir_offset" value="0.0"/>
  <xacro:property name="d415_cam_depth_to_right_ir_offset" value="-0.055"/>
  <xacro:property name="d415_cam_depth_to_color_offset" value="0.015"/>

  <!-- The following values model the aluminum peripherial case for the
  	d415 camera, with the camera joint represented by the actual
  	peripherial camera tripod mount -->
  <xacro:property name="d415_cam_width" value="0.099"/>
  <xacro:property name="d415_cam_height" value="0.023"/>
  <xacro:property name="d415_cam_depth" value="0.02005"/>
  <xacro:property name="d415_cam_mount_from_center_offset" value="0.00987"/>

  <!-- The following offset is relative the the physical d415 camera peripherial
  	camera tripod mount -->
  <xacro:property name="d415_cam_depth_px" value="${d415_cam_mount_from_center_offset}"/>
  <xacro:property name="d415_cam_depth_py" value="0.020"/>
  <xacro:property name="d415_cam_depth_pz" value="${d415_cam_height/2}"/>

  <material name="camera">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>

  <joint name="camera_joint" type="fixed">
    <!-- <origin xyz="0.1166 0.02 0.17092" rpy="0 0 0" /> -->
    <origin xyz="-0.002273 0.025225 1.1368" rpy="0 0 1.5708" />
    <parent link="base_link" />
    <child link="camera" />
    <axis xyz="0 0 0" />
  </joint>


  <link name="camera">
    <visual>
      <origin xyz="${d415_cam_mount_from_center_offset} ${-d415_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
      <geometry>
        <mesh filename="package://base_rover/meshes/d415.STL" />
      </geometry>
      <material name="camera"/>
    </visual>
    <collision>
      <origin xyz="0 ${-d415_cam_depth_py} 0" rpy="0 0 0"/>
      <geometry>
        <box size="${d415_cam_depth} ${d415_cam_width} ${d415_cam_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.564" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
    </inertial>
  </link>

  <!-- camera depth joints and links -->
  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="camera"/>
    <child link="camera_depth_frame" />
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
    <parent link="camera_depth_frame" />
    <child link="camera_depth_optical_frame" />
  </joint>
  <link name="camera_depth_optical_frame"/>

  <!-- camera left IR joints and links -->
  <joint name="camera_left_ir_joint" type="fixed">
    <origin xyz="0 ${d415_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
    <parent link="camera_depth_frame" />
    <child link="camera_left_ir_frame" />
  </joint>
  <link name="camera_left_ir_frame"/>

  <joint name="camera_left_ir_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
    <parent link="camera_left_ir_frame" />
    <child link="camera_left_ir_optical_frame" />
  </joint>
  <link name="camera_left_ir_optical_frame"/>

  <!-- camera right IR joints and links -->
  <joint name="camera_right_ir_joint" type="fixed">
    <origin xyz="0 ${d415_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
    <parent link="camera_depth_frame" />
    <child link="camera_right_ir_frame" />
  </joint>
  <link name="camera_right_ir_frame"/>

  <joint name="camera_right_ir_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
    <parent link="camera_right_ir_frame" />
    <child link="camera_right_ir_optical_frame" />
  </joint>
  <link name="camera_right_ir_optical_frame"/>

  <!-- camera color joints and links -->
  <joint name="camera_color_joint" type="fixed">
    <origin xyz="0 ${d415_cam_depth_to_color_offset} 0" rpy="0 0 0" />
    <parent link="camera_depth_frame" />
    <child link="camera_color_frame" />
  </joint>
  <link name="camera_color_frame"/>

  <joint name="camera_color_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
    <parent link="camera_color_frame" />
    <child link="camera_color_optical_frame" />
  </joint>
  <link name="camera_color_optical_frame"/>

</robot>
